### PR TITLE
Historical close data formatting

### PR DESCRIPTION
**Pull request by numel007**
### Checklist
- [ ] No merge conflicts (pull from `dev` if needed)
- [ ] Thoroughly tested code
- [ ] Trello card requirements are met

### What's new?
* Close data now formatted to rounded float
* Removed old files

### Known Issues
* n/a

### CODE REVIEW

**Review by pondorasti — APPROVED** [review]
Clean code!

**Comment by numel007** [comment]
Don't merge yet

**Comment by pondorasti** [comment]
🤦🏻

**Comment by numel007** [comment]
rip, I just noticed an issue with the server initializing

**Comment by pondorasti** [comment]
Btw, don't do rounding for historical. Try to commit again to this branch.

**Comment by numel007** [comment]
> Btw, don't do rounding for historical. Try to commit again to this branch.

I was just thinking that myself...

**Pull request merged**
